INSERT INTO artists (name_kr, name_eng, image_url, created_at, updated_at) VALUES('아이유', 'IU', 'https://i.scdn.co/image/ab6761610000e5eb006ff3c0136a71bfb9928d34', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO artists (name_kr, name_eng, image_url, created_at, updated_at) VALUES('장기하와 얼굴들', 'Kiha & The Faces', 'https://i.scdn.co/image/ab6761610000e5ebf99ecf9f9a5e0e62d01b10a6', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO artists (name_kr, name_eng, image_url, created_at, updated_at) VALUES('아이유아', 'Iua', 'https://i.scdn.co/image/ab6761610000e5ebf99ecf9f9a5e0e62d01b10a6', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO albums (title, image_url, release_date, total_tracks, artist_id, created_at, updated_at)  VALUES("IU 5th Album \'LILAC\'", 'https://i.scdn.co/image/ab67616d0000b2734ed058b71650a6ca2c04adff', '2021-03-25', 10, 1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO albums (title, image_url, release_date, total_tracks, artist_id, created_at, updated_at)  VALUES("Palette", 'https://i.scdn.co/image/ab67616d0000b273c06f0e8b33ac2d246158253e', '2017-04-21', 10, 1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO albums (title, image_url, release_date, total_tracks, artist_id, created_at, updated_at) VALUES("Modern Times – Epilogue", 'https://i.scdn.co/image/ab67616d0000b27315b8cef21bf4482d56c15614', '2013-12-20', 15, 1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO albums (title, image_url, release_date, total_tracks, artist_id, created_at, updated_at) VALUES("Last Fantasy", 'https://i.scdn.co/image/ab67616d0000b273bf5f4138ebc9ba3fd6f0cde9', '2011-11-29', 13, 1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO albums (title, image_url, release_date, total_tracks, artist_id, created_at, updated_at) VALUES("mono", 'https://i.scdn.co/image/ab67616d0000b273e5615d20fd403ca23486430a', '2018-11-01', 9, 2, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO albums (title, image_url, release_date, total_tracks, artist_id, created_at, updated_at) VALUES("새해 복 Remix 2018", 'https://i.scdn.co/image/ab67616d0000b273a026e2391a8965a17396f472', '2018-02-05', 7, 2, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO albums (title, image_url, release_date, total_tracks, artist_id, created_at, updated_at) VALUES("내 사랑에 노련한 사람이 어딨나요", 'https://i.scdn.co/image/ab67616d0000b2733fe5b307265437a9349a2773', '2016-06-16', 10, 2, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
insert into tracks (title, duration, artist_id, album_id, created_at, updated_at) values('라일락', '3:35', 1, 1, current_timestamp(), current_timestamp());
insert into tracks (title, duration, artist_id, album_id, created_at, updated_at) values('Flu', '3:35', 1, 1, current_timestamp(), current_timestamp());
insert into tracks (title, duration, artist_id, album_id, created_at, updated_at) values('Coin', '3:35', 1, 1, current_timestamp(), current_timestamp());
insert into tracks (title, duration, artist_id, album_id, created_at, updated_at) values('봄 안녕 봄', '3:35', 1, 1, current_timestamp(), current_timestamp());
insert into tracks (title, duration, artist_id, album_id, created_at, updated_at) values('Celebrity', '3:35', 1, 1, current_timestamp(), current_timestamp());
insert into tracks (title, duration, artist_id, album_id, created_at, updated_at) values('돌림노래 (Feat. DEAN)', '3:35', 1, 1, current_timestamp(), current_timestamp());
insert into tracks (title, duration, artist_id, album_id, created_at, updated_at) values('빈 컵 (Empty Cup)', '3:35', 1, 1, current_timestamp(), current_timestamp());
insert into tracks (title, duration, artist_id, album_id, created_at, updated_at) values('아이와 나의 바다', '3:35', 1, 1, current_timestamp(), current_timestamp());
insert into tracks (title, duration, artist_id, album_id, created_at, updated_at) values('어푸 (Ah puh)', '3:35', 1, 1, current_timestamp(), current_timestamp());
insert into tracks (title, duration, artist_id, album_id, created_at, updated_at) values('에필로그', '3:35', 1, 1, current_timestamp(), current_timestamp());
insert into tracks (title, duration, artist_id, album_id, created_at, updated_at) values('이 지금', '3:35', 1, 2, current_timestamp(), current_timestamp());
insert into tracks (title, duration, artist_id, album_id, created_at, updated_at) values('팔레트 (Feat. G-DRAGON)', '3:35', 1, 2, current_timestamp(), current_timestamp());
insert into tracks (title, duration, artist_id, album_id, created_at, updated_at) values('이런 엔딩', '3:35', 1, 2, current_timestamp(), current_timestamp());
insert into tracks (title, duration, artist_id, album_id, created_at, updated_at) values('사랑이 잘 (With 오혁)', '3:35', 1, 2, current_timestamp(), current_timestamp());
insert into tracks (title, duration, artist_id, album_id, created_at, updated_at) values('잼잼', '3:35', 1, 2, current_timestamp(), current_timestamp());
insert into tracks (title, duration, artist_id, album_id, created_at, updated_at) values('Black Out', '3:35', 1, 2, current_timestamp(), current_timestamp());
insert into tracks (title, duration, artist_id, album_id, created_at, updated_at) values('마침표', '3:35', 1, 2, current_timestamp(), current_timestamp());
insert into tracks (title, duration, artist_id, album_id, created_at, updated_at) values('밤편지', '3:35', 1, 2, current_timestamp(), current_timestamp());
insert into tracks (title, duration, artist_id, album_id, created_at, updated_at) values('그렇게 사랑은', '3:35', 1, 2, current_timestamp(), current_timestamp());
insert into tracks (title, duration, artist_id, album_id, created_at, updated_at) values('이름에게', '3:35', 1, 2, current_timestamp(), current_timestamp());
insert into tracks (title, duration, artist_id, album_id, created_at, updated_at) values('그건 니 생각이고', '3:35', 2, 5, current_timestamp(), current_timestamp());
insert into tracks (title, duration, artist_id, album_id, created_at, updated_at) values('거절할 거야', '3:35', 2, 5, current_timestamp(), current_timestamp());
insert into tracks (title, duration, artist_id, album_id, created_at, updated_at) values('나란히 나란히', '3:35', 2, 5, current_timestamp(), current_timestamp());
insert into tracks (title, duration, artist_id, album_id, created_at, updated_at) values('나와의 채팅', '3:35', 2, 5, current_timestamp(), current_timestamp());
insert into tracks (title, duration, artist_id, album_id, created_at, updated_at) values('등산은 왜 할까', '3:35', 2, 5, current_timestamp(), current_timestamp());
insert into tracks (title, duration, artist_id, album_id, created_at, updated_at) values('아무도 필요 없다', '3:35', 2, 5, current_timestamp(), current_timestamp());
insert into tracks (title, duration, artist_id, album_id, created_at, updated_at) values('나 혼자', '3:35', 2, 5, current_timestamp(), current_timestamp());
insert into tracks (title, duration, artist_id, album_id, created_at, updated_at) values('초심', '3:35', 2, 5, current_timestamp(), current_timestamp());
insert into tracks (title, duration, artist_id, album_id, created_at, updated_at) values('별거 아니라고', '3:35', 2, 5, current_timestamp(), current_timestamp());
insert into tracks (title, duration, artist_id, album_id, created_at, updated_at) values('내 사랑에 노련한 사람이 어딨나요', '3:35', 2, 7, current_timestamp(), current_timestamp());
insert into tracks (title, duration, artist_id, album_id, created_at, updated_at) values('ㅋ', '3:35', 2, 5, current_timestamp(), current_timestamp());
insert into tracks (title, duration, artist_id, album_id, created_at, updated_at) values('괜찮아요', '3:35', 2, 5, current_timestamp(), current_timestamp());
insert into tracks (title, duration, artist_id, album_id, created_at, updated_at) values('그러게 왜 그랬어', '3:35', 2, 5, current_timestamp(), current_timestamp());
insert into tracks (title, duration, artist_id, album_id, created_at, updated_at) values('가장 아름다운 노래', '3:35', 2, 5, current_timestamp(), current_timestamp());
insert into tracks (title, duration, artist_id, album_id, created_at, updated_at) values('가나다', '3:35', 2, 5, current_timestamp(), current_timestamp());
insert into tracks (title, duration, artist_id, album_id, created_at, updated_at) values('빠지기는 빠지더라', '3:35', 2, 5, current_timestamp(), current_timestamp());
insert into tracks (title, duration, artist_id, album_id, created_at, updated_at) values('쌀밥', '3:35', 2, 5, current_timestamp(), current_timestamp());
insert into tracks (title, duration, artist_id, album_id, created_at, updated_at) values('살결', '3:35', 2, 5, current_timestamp(), current_timestamp());
insert into tracks (title, duration, artist_id, album_id, created_at, updated_at) values('오늘 같은 날', '3:35', 2, 5, current_timestamp(), current_timestamp());
